# Market Data Collection

This notebook collects five years of historical market data for the selected ETFs and stocks using Yahoo Finance.

## 1. setup and imports

In [63]:

import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as pyplot
from pathlib import Path
from datetime import datetime
from dateutil.relativedelta import relativedelta

## define of assets

In [64]:

etfs = ['VNQ','VXUS','SCHD','VOO','QQQM','FXAIX']
stocks =['AMZN','AAPL','MSFT','NVDA']
tickers = etfs + stocks

## 3. Define Analysis Period

In [65]:
from datetime import date


start_date = '2021-10-01'
end_date = date.today()
start_date = end_date - relativedelta(years=5)

## 4.Download the historical market data

In [66]:
market_data = yf.download(
    tickers,
    start=start_date,
    auto_adjust=False,
    group_by="column"
)

[*********************100%***********************]  10 of 10 completed

## 6. Data Validation

In [67]:
market_data.head()

Price        Adj Close                                                 \
Ticker            AAPL        AMZN       FXAIX        MSFT       NVDA
Date
2021-10-01  139.136642  164.162994  141.417313  277.457153  20.651039
2021-10-04  135.713135  159.488998  139.592850  271.708374  19.645468
2021-10-05  137.634613  161.050003  141.080460  277.130859  20.361319
2021-10-06  138.502716  163.100494  141.660583  281.305634  20.609222
2021-10-07  139.760941  165.121506  142.867493  282.975586  20.982580

Price                                                                ...  \
Ticker            QQQM       SCHD        VNQ         VOO       VXUS  ...
Date                                                                 ...
2021-10-01  143.428864  20.978327  84.965584  372.080322  54.441944  ...
2021-10-04  140.502701  20.894670  84.982048  367.503052  53.875549  ...
2021-10-05  142.314621  21.020153  84.397614  371.073547  54.201660  ...
2021-10-06  143.283524  21.053614  85.204315  372.723602  53.884136  ...
2021-10-07  144.543106  21.212568  85.434784  375.930573  54.502003  ...

Price         Volume                                                          \
Ticker          AAPL      AMZN FXAIX      MSFT       NVDA     QQQM      SCHD
Date
2021-10-01  94639600  56712000     0  30086300  240978000   786500   6019800
2021-10-04  98322000  90462000     0  31350700  345635000  1071800  13274700
2021-10-05  80861100  65384000     0  24993000  279282000  1172800   4444500
2021-10-06  83221100  50660000     0  28002600  297202000   729900   5120400
2021-10-07  61732700  48182000     0  20430500  256919000   369000   3742800

Price
Ticker          VNQ      VOO     VXUS
Date
2021-10-01  6106100  8482200  3007100
2021-10-04  5638600  8820400  4093400
2021-10-05  4313800  5523200  2395000
2021-10-06  5587900  6590000  3441400
2021-10-07  4055300  4409200  2470400

[5 rows x 60 columns]

In [68]:
market_data.shape

(1255, 60)

In [69]:

market_data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1255 entries, 2021-10-01 to 2026-10-01
Data columns (total 60 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   (Adj Close, AAPL)   1255 non-null   float64
 1   (Adj Close, AMZN)   1255 non-null   float64
 2   (Adj Close, FXAIX)  1255 non-null   float64
 3   (Adj Close, MSFT)   1255 non-null   float64
 4   (Adj Close, NVDA)   1255 non-null   float64
 5   (Adj Close, QQQM)   1255 non-null   float64
 6   (Adj Close, SCHD)   1255 non-null   float64
 7   (Adj Close, VNQ)    1255 non-null   float64
 8   (Adj Close, VOO)    1255 non-null   float64
 9   (Adj Close, VXUS)   1255 non-null   float64
 10  (Close, AAPL)       1255 non-null   float64
 11  (Close, AMZN)       1255 non-null   float64
 12  (Close, FXAIX)      1255 non-null   float64
 13  (Close, MSFT)       1255 non-null   float64
 14  (Close, NVDA)       1255 non-null   float64
 15  (Close, QQQM)       1255 non-null   float64
 16  (Close, SCHD)       1255 non-null   float64
 17  (Close, VNQ)        1255 non-null   float64
 18  (Close, VOO)        1255 non-null   float64
 19  (Close, VXUS)       1255 non-null   float64
 20  (High, AAPL)        1255 non-null   float64
 21  (High, AMZN)        1255 non-null   float64
 22  (High, FXAIX)       1255 non-null   float64
 23  (High, MSFT)        1255 non-null   float64
 24  (High, NVDA)        1255 non-null   float64
 25  (High, QQQM)        1255 non-null   float64
 26  (High, SCHD)        1255 non-null   float64
 27  (High, VNQ)         1255 non-null   float64
 28  (High, VOO)         1255 non-null   float64
 29  (High, VXUS)        1255 non-null   float64
 30  (Low, AAPL)         1255 non-null   float64
 31  (Low, AMZN)         1255 non-null   float64
 32  (Low, FXAIX)        1255 non-null   float64
 33  (Low, MSFT)         1255 non-null   float64
 34  (Low, NVDA)         1255 non-null   float64
 35  (Low, QQQM)         1255 non-null   float64
 36  (Low, SCHD)         1255 non-null   float64
 37  (Low, VNQ)          1255 non-null   float64
 38  (Low, VOO)          1255 non-null   float64
 39  (Low, VXUS)         1255 non-null   float64
 40  (Open, AAPL)        1255 non-null   float64
 41  (Open, AMZN)        1255 non-null   float64
 42  (Open, FXAIX)       1255 non-null   float64
 43  (Open, MSFT)        1255 non-null   float64
 44  (Open, NVDA)        1255 non-null   float64
 45  (Open, QQQM)        1255 non-null   float64
 46  (Open, SCHD)        1255 non-null   float64
 47  (Open, VNQ)         1255 non-null   float64
 48  (Open, VOO)         1255 non-null   float64
 49  (Open, VXUS)        1255 non-null   float64
 50  (Volume, AAPL)      1255 non-null   int64
 51  (Volume, AMZN)      1255 non-null   int64
 52  (Volume, FXAIX)     1255 non-null   int64
 53  (Volume, MSFT)      1255 non-null   int64
 54  (Volume, NVDA)      1255 non-null   int64
 55  (Volume, QQQM)      1255 non-null   int64
 56  (Volume, SCHD)      1255 non-null   int64
 57  (Volume, VNQ)       1255 non-null   int64
 58  (Volume, VOO)       1255 non-null   int64
 59  (Volume, VXUS)      1255 non-null   int64
dtypes: float64(50), int64(10)
memory usage: 598.1 KB

In [70]:
market_data.tail()

Price        Adj Close                                                  \
Ticker            AAPL        AMZN       FXAIX        MSFT        NVDA
Date
2026-09-25  341.070007  249.669998  269.700012  516.169983  225.070007
2026-09-28  338.399994  246.149994  267.619995  509.220001  228.860001
2026-09-29  329.399994  246.669998  267.170013  508.959991  227.210007
2026-09-30  333.019989  249.149994  266.529999  512.900024  228.380005
2026-10-01  330.320007  248.229996  267.049988  512.799988  230.860001

Price                                                                ...  \
Ticker            QQQM       SCHD        VNQ         VOO       VXUS  ...
Date                                                                 ...
2026-09-25  306.540009  33.209999  90.989998  708.966980  86.349998  ...
2026-09-28  303.290009  33.009998  90.589996  703.609985  85.750000  ...
2026-09-29  303.829987  32.849998  90.529999  702.460022  85.519997  ...
2026-09-30  304.640015  32.529999  89.629997  700.859985  84.959999  ...
2026-10-01  305.570007  32.660000  89.169998  702.349976  84.459999  ...

Price         Volume                                                          \
Ticker          AAPL      AMZN FXAIX      MSFT       NVDA     QQQM      SCHD
Date
2026-09-25  30002500  34263900     0  38193100   89947700  2456700  23798900
2026-09-28  32820800  32596700     0  19626900  142344300  2391700  27620300
2026-09-29  38478000  33730400     0  21341800  101494900  1886900  25686000
2026-09-30  49988600  41913100     0  27223300  121732200  2937200  21092600
2026-10-01  36243900  33173500     0  19696600   98369800  3412700  23939200

Price
Ticker          VNQ      VOO     VXUS
Date
2026-09-25  6148800  5462300  4235200
2026-09-28  4723700  8539400  6663300
2026-09-29  5032700  7643300  5182300
2026-09-30  4705400  9876100  4726300
2026-10-01  7406800  8175700  6524100

[5 rows x 60 columns]

In [71]:
market_data.isna().sum()

Price      Ticker
Adj Close  AAPL      0
           AMZN      0
           FXAIX     0
           MSFT      0
           NVDA      0
           QQQM      0
           SCHD      0
           VNQ       0
           VOO       0
           VXUS      0
Close      AAPL      0
           AMZN      0
           FXAIX     0
           MSFT      0
           NVDA      0
           QQQM      0
           SCHD      0
           VNQ       0
           VOO       0
           VXUS      0
High       AAPL      0
           AMZN      0
           FXAIX     0
           MSFT      0
           NVDA      0
           QQQM      0
           SCHD      0
           VNQ       0
           VOO       0
           VXUS      0
Low        AAPL      0
           AMZN      0
           FXAIX     0
           MSFT      0
           NVDA      0
           QQQM      0
           SCHD      0
           VNQ       0
           VOO       0
           VXUS      0
Open       AAPL      0
           AMZN      0
           FXAIX     0
           MSFT      0
           NVDA      0
           QQQM      0
           SCHD      0
           VNQ       0
           VOO       0
           VXUS      0
Volume     AAPL      0
           AMZN      0
           FXAIX     0
           MSFT      0
           NVDA      0
           QQQM      0
           SCHD      0
           VNQ       0
           VOO       0
           VXUS      0
dtype: int64

In [72]:
market_data['Adj Close'].columns

Index(['AAPL', 'AMZN', 'FXAIX', 'MSFT', 'NVDA', 'QQQM', 'SCHD', 'VNQ', 'VOO',
       'VXUS'],
      dtype='str', name='Ticker')

## 6. Save Raw Data

In [74]:
raw_data_path = Path("../data/raw")
raw_data_path.mkdir(parents=True, exist_ok=True)

market_data.to_csv(raw_data_path / "market_data.csv")

print("Raw market data saved successfully.")

Raw market data saved successfully.

In [78]:
raw_data = pd.read_csv(
    raw_data_path / "market_data.csv",
    header=[0, 1],
    index_col=0,
    parse_dates=True
)

print("Saved shape:", raw_data.shape)
raw_data.head()

Saved shape: (1255, 60)

Price        Adj Close                                                 \
Ticker            AAPL        AMZN       FXAIX        MSFT       NVDA
Date
2021-10-01  139.136642  164.162994  141.417313  277.457153  20.651039
2021-10-04  135.713135  159.488998  139.592850  271.708374  19.645468
2021-10-05  137.634613  161.050003  141.080460  277.130859  20.361319
2021-10-06  138.502716  163.100494  141.660583  281.305634  20.609222
2021-10-07  139.760941  165.121506  142.867493  282.975586  20.982580

Price                                                                ...  \
Ticker            QQQM       SCHD        VNQ         VOO       VXUS  ...
Date                                                                 ...
2021-10-01  143.428864  20.978327  84.965584  372.080322  54.441944  ...
2021-10-04  140.502701  20.894670  84.982048  367.503052  53.875549  ...
2021-10-05  142.314621  21.020153  84.397614  371.073547  54.201660  ...
2021-10-06  143.283524  21.053614  85.204315  372.723602  53.884136  ...
2021-10-07  144.543106  21.212568  85.434784  375.930573  54.502003  ...

Price         Volume                                                          \
Ticker          AAPL      AMZN FXAIX      MSFT       NVDA     QQQM      SCHD
Date
2021-10-01  94639600  56712000     0  30086300  240978000   786500   6019800
2021-10-04  98322000  90462000     0  31350700  345635000  1071800  13274700
2021-10-05  80861100  65384000     0  24993000  279282000  1172800   4444500
2021-10-06  83221100  50660000     0  28002600  297202000   729900   5120400
2021-10-07  61732700  48182000     0  20430500  256919000   369000   3742800

Price
Ticker          VNQ      VOO     VXUS
Date
2021-10-01  6106100  8482200  3007100
2021-10-04  5638600  8820400  4093400
2021-10-05  4313800  5523200  2395000
2021-10-06  5587900  6590000  3441400
2021-10-07  4055300  4409200  2470400

[5 rows x 60 columns]